# Generated by Django 5.1.6 on 2025-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userfinancialprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='savings_percent',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('50%+', '50%+')], max_length=5),
        ),
    ]
