# Generated by Django 5.1.6 on 2025-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('savings_investment', 'Savings & Investment')], max_length=20),
        ),
    ]
