# Generated by Django 5.1.6 on 2025-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
