# Generated by Django 5.1.6 on 2025-02-24 15:12

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(validators=[profiles.models.validate_positive]),
        ),
    ]
