# Generated by Django 5.1.6 on 2025-02-24 15:20

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='monthly_income',
            field=models.FloatField(validators=[profiles.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='monthly_spending_goal',
            field=models.FloatField(validators=[profiles.models.validate_positive]),
        ),
    ]
