# Generated by Django 5.1.6 on 2025-02-24 19:27

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userfinancialprofile_monthly_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='monthly_income',
            field=models.FloatField(validators=[profiles.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='monthly_spending_goal',
            field=models.FloatField(validators=[profiles.models.validate_positive]),
        ),
    ]
