# Generated by Django 5.1.6 on 2025-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_userfinancialprofile_monthly_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
