# Generated by Django 5.1.6 on 2025-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_transaction_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nextOccur',
            field=models.DateField(blank=True, null=True),
        ),
    ]
