# Generated by Django 5.1.7 on 2025-03-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_transaction_nextoccur'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinancialprofile',
            name='first_name',
            field=models.CharField(blank=True, default='Not provided', max_length=50),
        ),
        migrations.AddField(
            model_name='userfinancialprofile',
            name='last_name',
            field=models.CharField(blank=True, default='Not provided', max_length=50),
        ),
    ]
