# Generated by Django 5.1.7 on 2025-04-03 19:16

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_userfinancialprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[profiles.models.validate_positive]),
        ),
    ]
