# Generated by Django 5.1.7 on 2025-04-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='merchant',
        ),
    ]
